################
# Unmanic Docker Compose template
#
# Use this template when enabling AMD GPU Hardware accelerated encoding
#
# Variables that will need to be changed:
#     <PUID>                            -  User id for folder/file permissions
#     <PGID>                            -  Group id for folder/file permissions
#     <TZ>                              -  Your time zone, eg - Pacific/Auckland
#     <PATH_TO_CONFIG>                  -  Path where Unmanic will store config files
#     <PATH_TO_LIBRARY>                 -  Path where you store the files that Unmanic will scan
#     <PATH_TO_ENCODE_CACHE>            -  Cache path for in-progress encoding tasks
#     <AMD_GPU_DEVICE>                  -  Specific AMD GPU device path (optional)
#                                          Examples: /dev/dri/renderD128, /dev/dri/renderD129
#                                          Leave empty to use all available AMD GPUs
#


version: '2.4'

services:
  unmanic:
    container_name: unmanic
    image: josh5/unmanic:latest
    ports:
      - 8888:8888
    environment:
      - PUID=<PUID>
      - PGID=<PGID>
      - TZ=<TZ>
      # AMD-specific environment variables
      - RADV_PERFTEST=1
      - AMD_VULKAN_ICD=RADV
      - LIBVA_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri
    volumes:
      - <PATH_TO_CONFIG>:/config
      - <PATH_TO_LIBRARY>:/library
      - <PATH_TO_ENCODE_CACHE>:/tmp/unmanic
    devices:
      # For AMD GPU hardware acceleration using VAAPI
      - /dev/dri:/dev/dri
      # Optional: For ROCm compute support (if available)
      # - /dev/kfd:/dev/kfd
      # Optional: For specific AMD GPU device
      # - <AMD_GPU_DEVICE>:<AMD_GPU_DEVICE>
